"""Entity and relationship extraction interfaces."""

from saga_companion.extract.adapters import (
    event_from_dict,
    event_to_dict,
    evidence_from_dict,
    evidence_to_dict,
    passage_extraction_from_dict,
    passage_extraction_to_dict,
    person_from_dict,
    person_to_dict,
    place_from_dict,
    place_to_dict,
    relationship_from_dict,
    relationship_to_dict,
)
from saga_companion.extract.parser import (
    ExtractionParseError,
    extract_json_object,
    parse_passage_extraction_response,
)
from saga_companion.extract.prompts import (
    ExtractionPrompt,
    build_passage_extraction_prompt,
    event_type_values,
    expected_extraction_json_shape,
    relationship_type_values,
)
from saga_companion.extract.schemas import (
    EventType,
    EvidenceRef,
    ExtractedEntityType,
    ExtractedEvent,
    ExtractedPerson,
    ExtractedPlace,
    ExtractedRelationship,
    PassageExtraction,
    RelationshipType,
    empty_passage_extraction,
)

__all__ = [
    "EventType",
    "ExtractionParseError",
    "ExtractionPrompt",
    "EvidenceRef",
    "ExtractedEntityType",
    "ExtractedEvent",
    "ExtractedPerson",
    "ExtractedPlace",
    "ExtractedRelationship",
    "PassageExtraction",
    "RelationshipType",
    "build_passage_extraction_prompt",
    "event_from_dict",
    "event_type_values",
    "event_to_dict",
    "evidence_from_dict",
    "evidence_to_dict",
    "empty_passage_extraction",
    "extract_json_object",
    "expected_extraction_json_shape",
    "passage_extraction_from_dict",
    "passage_extraction_to_dict",
    "parse_passage_extraction_response",
    "person_from_dict",
    "person_to_dict",
    "place_from_dict",
    "place_to_dict",
    "relationship_from_dict",
    "relationship_type_values",
    "relationship_to_dict",
]
